image: ubuntu:16.04

# TODO:
# Create an Ubuntu image with all of these dependencies
# already installed. This could save time because update
# and install will need to be done for EACH job (build,
# run tests, run app) triggered.
before_script:
  - apt-get update --yes
  - apt-get install --yes g++=4:5.3.1-1ubuntu1
  - apt-get install --yes lcov=1.12-2
  - apt-get install --yes cmake=3.5.1-1ubuntu3
  - apt-get install --yes git=1:2.7.4-0ubuntu1.6
  - apt-get install --yes libpthread-stubs0-dev=0.3-4
  - rm -Rf build
  - mkdir build
  - cd build
  - cmake ..
  - make -j8

# Tell gitlab-runner to share the build/
# directory in between jobs (because
# this is where we store our CMake outputs)
cache:
  paths:
    - build/

run tests:
  only:
    - master
  tags:
    - commonpf
    - cpp
    - tests
  script:
    - ./bin/calculator_tests
    - ls -l
    - cd CMakeFiles/calculator_tests.dir/
    - ls -l
    - lcov -d . -c -o coverage.info
    - lcov -r coverage.info */build/* */tests/* */c++/* -o coverageFiltered.info
    - lcov --list coverageFiltered.info
  coverage: '/Total.*\s+(\d+%).*$/'
