image: ubuntu:16.04

stages:
  - build
  - test

before_script:
  - apt-get update --yes
  - apt-get install --yes cmake=3.5.1-1ubuntu3
  - apt-get install --yes git=1:2.7.4-0ubuntu1.6
  - apt-get install --yes libpthread-stubs0-dev=0.3-4

# Tell gitlab-runner to share the build/
# directory in between jobs (because
# this is where we store our CMake outputs)
cache:
  paths:
    - build/

build:
  stage: build
  tags:
    - commonpf
    - cpp
    - build
  script:
    - cd build
    - cmake ..
    - make

run tests:
  stage: test
  only:
    - master
  tags:
    - commonpf
    - cpp
    - tests
  script:
    - ./build/bin/calculator_tests
